module.exports = {
  env: {
    NEXTAUTH_URL: process.env.NEXTAUTH_URL,
    CLOUDINARY_UPLOAD_PRESET: process.env.CLOUDINARY_UPLOAD_PRESET,
    CLOUDINARY_CLOUD_NAME: process.env.CLOUDINARY_CLOUD_NAME,
    GOOGLE_APPLICATION_CREDENTIAL: process.env.GOOGLE_APPLICATION_CREDENTIAL,
  },
};
